export const RECIPES_GET = 'RECIPES_GET';
export const ORDER_RECIPES = 'ORDER_RECIPES'
export const FILTER_RECIPES = 'FILTER_RECIPES'
export const DIETS_GET = 'DIETS_GET'
export const FILTER_DB_API = 'FILTER_DB_API'
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES' 